export default {
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UPDATE_FAILED: "UPDATE_FAILED",
  CREATION_FAILED: "CREATION_FAILED",
  DELETE_FAILTED: "DELETE_FAILED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_TYPE: "INVALID_TYPE",
  ALREADY_EXIST: "ALREADY EXIST",
};
