export default {
  SUCCESSFULLY_AUTHORIZED: "SUCCESSFULLY_AUTHORIZED",
  SUCCESSFULLY_DATA_RETRIVED: "SUCCESSFULLY_DATA_RETRIVED",
  SUCCESSFULLY_DATA_ADDED: "SUCCESSFULLY_DATA_ADDED",
  SUCCESSFULLY_DATA_UPDATED: "SUCCESSFULLY_DATA_UPDATED",
  SUCCESSFULLY_DATA_DELETED: "SUCCESSFULLY_DATA_DELETED",
};
